#!/usr/bin/env python
"""
Copyright 2012 Wordnik, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class AttachmentEntry:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            'content': 'str',
            'name': 'str',
            'mimeType': 'str'

        }


        #File content as a Base64 encoded string
        self.content = None # str
        #Name of the file
        self.name = None # str
        #MIME content type. Use 'application/octet-stream' for pdfs, docs, binary files
        self.mimeType = None # str
        
